#checkov:skip=CKV2_GHA_1 ignore ensure top-level permissions are not set to write-all
name: "Build_TF_Plan"
permissions:
  id-token: write
  contents: read
  issues: read
on:
  workflow_call:
    inputs:
      path:
        description: "Specifies the path of the root terraform module."
        required: true
        type: string
      gh_environment:
        description: "Specifies the GitHub deployment environment."
        required: false
        type: string
        default: null
      enable_TFSEC:
        description: "(Optional) Enables TFSEC IaC scans and code quality checks on Terraform configurations"
        required: false
        type: boolean
        default: false
    secrets:
      aws_role_to_assume:
        description: "Specifies the AWS_GITHUB_ACTION_ROLE."
        required: true
      aws_default_region:
        description: "Specifies the AWS_DEFAULT_REGION."
        required: true
      terraform_version:
        description: "Specifies the TERRAFORM_VERSION."
        required: true
      deploy_key:
        description: "Specifies the DEPLOY_KEY"
        required: true

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
    env:
      ###AWS Provider details###
      AWS_GITHUB_ACTION_ROLE: ${{ secrets.aws_role_to_assume }}
      TERRAFORM_VERSION: ${{ secrets.terraform_version }}
      DEPLOY_KEY: ${{ secrets.deploy_key }}
      working_dir: 'eu-west-2/datascience/wise'
    
    # strategy:
    #   matrix:
    #     environment: [dev, stage, prod]

    steps:
      # TFLint Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v3  
        
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}
          
      # Print TFLint version
      - name: Show version
        run: tflint --version
        
      # Install plugins
      - name: Init TFLint
        run: tflint --init

    # TFLint - Terraform Check
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
        
      # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
      - name: Run TFLint
        run: tflint -f compact --recursive

      # TFSec Checkout Repository
      - name: Clone repo
        uses: actions/checkout@master
        with:
          persist-credentials: false

      # - name: tfsec Terraform security scan
      #   uses: tfsec/tfsec-sarif-action@v0.1.0 #aquasecurity/tfsec-action@v1.0.0
      #   with:
      #     format: json
      #     sarif_file: tfsec.sarif
      #     github_token: ${{ secrets.GITHUB_TOKEN }}  

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: tfsec.sarif

      - name: Pull Request Commenter
        if: ${{ github.event_name == 'pull_request' }} 
        uses: tfsec/tfsec-pr-commenter-action@main #aquasecurity/tfsec-pr-commenter-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: tfsec scan result
      #   run: |
      #     #docker run -t -v "$(pwd)" aquasec/tfsec ${{ inputs.path }} --format json
      #     docker run -t -v "$(pwd)" aquasec/tfsec .

      - name: tfsec security scan
        run: |
          curl -L https://github.com/aquasecurity/tfsec/releases/download/v1.28.14/tfsec-linux-amd64 -o tfsec
          chmod +x tfsec
          ./tfsec .

      # checkov-checks checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v2
      
      # Checkov - Prevent cloud misconfigurations and find vulnerabilities during build-time in infrastructure as code
      # - name: Run Checkov
      #   run: |
      #     docker run -t -v ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --skip-check CKV2_GHA_1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ secrets.aws_default_region }}

      # Terraform checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ secrets.terraform_version }}
          tg_dir: ${{ inputs.path }}/${{ env.working_dir }}

      - name: Terraform Init
        id: init
        run: terraform init -get=true -input=false -reconfigure

      # Run a terraform fmt to check syntax
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -check -diff

      # Run a terraform validate
      - name: Terraform Validate
        id: validate
        # Run even if formatting fails
        if: success() || failure()
        run: terraform validate

      # Run a terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false -refresh=true -var-file=${{ inputs.path }}.tfvars
