name: "production deployment"
permissions:
  id-token: write
  contents: read
  issues: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Plan_Prod:
    #uses: linh5847/aws-terraform-github-action-cicd/.github/workflows/az_tf_plan.yml@main # @main means github branch
    uses: ./.github/workflows/az_tf_plan.yml
    with:
      path: dev
      enable_TFSEC: true ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
      aws_default_region: eu-west-2
      terraform_version: ${{ secrets.TERRAFORM_VERSION }}
      deploy_key: ${{secrets.DEPLOY_KEY }}

  Deploy_Prod:
    needs: Plan_Prod
    uses: ./.github/workflows/az_tf_apply.yml
    with:
      path: dev
    secrets:
      aws_role_to_assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
      aws_default_region: eu-west-2
      terraform_version: ${{ secrets.TERRAFORM_VERSION }}
      deploy_key: ${{secrets.DEPLOY_KEY }}